##############################################
# START YOUR CONFIGURATION HERE! For more info, visit https://digitalarcplatform.kalanicraig.com/quickstart
#---------------------
# THEME. Leave Lines 4-6 alone.
#---------------------
remote_theme: kalanicraig/digitalarcplatform@v1.0.0
repository: 'vercellimtd/vercellimtd.github.io' # change this to your repository name

##############################################
# WHAT IS ALL THIS STUFF?
#---------------------
# _config is easy. Most web sites have configuration files.
# .yml means YAML. It's the data that runs your site.
# Some files, like this one, are entirely made up of YAML.
# Lines with information that isn't YAML are commented out; the lines start with #
# Those lines will be ignored by the computer but provide important information to you.
#
##############################################
# WHAT DO I DO NOW?
#---------------------
# Look for the lines that have a bunch of ### in row.
# These break _config.yml into sections.
# You'll need to do something slightly different in each section.
# If you see an instruction to "comment out", add a # to the beginning of the line(s).
# If you see an instruction to "uncomment", remove the # at the beginning of the line(s).

##############################################
# THE MOST IMPORTANT THING TO REMEMBER
#---------------------
# Variables are the things that drive your site.
# In YAML, there's a variable name--a placeholder--at the beginning of the line.
# Variables have colons after them in YAML.
# After the variable comes the actual contents of the variable, usually in double quotes
#               title: "Your Site Title"
# If you use another double quote inside your variable, it will break this config file.
#               title: "My "So-Called" Website"
#
##############################################
# START CUSTOMIZING YOUR SITE HERE
##############################################
# ABOUT YOUR SITE
#---------------------

# Title of your website
title: "La Fondazione Museo del Tesoro del Duomo e Archivio Capitolare di Vercelli"

# Subtitle of your website. Leave blank if you want to.
subtitle: "Trasmettiamo la cultura al futuro e svolgiamo attività di ricerca, valorizzazione e tutela"

# A longer description of your site (max 150 words). Helps search engines find you.
description: "Il suo scopo è preservare e diffondere la conoscenza, la storia e le tradizioni legate al patrimonio artistico, librario e archivistico del Capitolo della Cattedrale di S. Eusebio e dell’Arcidiocesi di Vercelli, la più antica del Piemonte. All’interno di Museo del Tesoro del Duomo, Biblioteca e Archivio Capitolare le molteplici testimonianze mettono in connessione il passato e il presente."

# These credits show up in the includes/_footer.html
# Main author of the website.
author: "VercelliMTD"
authorname : "Vercelli MTD "

# To change the photo on your homepage, open the assets folder in your Github repo, then open the img folder. Upload a photo there. Add only the name of the photo and its extension here. E.g. "alternate_logo.png")
sitelogo: "site_logo.png"
placeholderimg: "placeholder.png"

# What year did you start up this community project?
sitedate : 2022

# Other community social media. Leave blank if you don't have these.
email : "info at tesorodelduomovc.it"
website : "https://tesorodelduomovc.it"
twitter : ""
github : ""
facebook : ""
instagram : ""

# If you need to know how many people visit your site, go to https://analytics.google.com/
# When you finish the setup assistant, it will give you a Measurement ID: G-ABCDEFGHIJ
google_g4_analytics_id: UA-73553056-5

##############################################
# FONTS AND COLORS
#---------------------

# Choose the FONTS you'd like to use.
# You can see these font choices in action at https://digitalarcplatform.kalanicraig.com/docs/
# Uncomment the line for the font you like. Comment out all of the other lines.

fontchoice: custom

# Choose the COLORS you'd like to use.
# You can see these color choices in action at https://digitalarcplatform.kalanicraig.com/docs/
# Uncomment the line for the color you like. Comment out all of the other lines.

colorchoice: custom

# If you chose white with an accent color, choose the ACCENT you'd like to use.
# You can see these color choices in action at https://digitalarcplatform.kalanicraig.com/docs/
# Uncomment the line for the color you like. Comment out all of the other lines.

accentchoice: accent-custom
##############################################
# ORGANIZING YOUR COLLECTION
#---------------------
# These collections take the basic files you put together for each item in your collection and auto-group and display them.
# This takes each item in your archive collection and displays it
collections:
  items:
    output: true
    permalink: /:collection/:path:output_ext
    contributor: true
    creator: true
    mss: true
# If your collection items need to be grouped by person, family or some other group, uncomment this collection
  mss:
    output: true
    permalink: /:collection/:path:output_ext
    name: true
    folder: true
    sort_by: foliosort
# If you have oral histories that go with groups, uncomment this collection:
#  oralhistories:
#    output: true
#    permalink: /:collection/:path:output_ext
#    name: true
#    folder: true
#    sort_by: folder
  authors:
    output: false
    name: true

##############################################
# WEBSITE ORGANIZATION
#---------------------
# MOST OF THESE THINGS DON'T NEED TO BE CHANGED.
##############################################

# This URL is the main address for absolute links. This will usually be blank.
url: 
# If this archive will be in a folder (kalanicraig.com/digitalarcplatform/) instead of in its own main site (digitalarcplatform.github.io) add that folder name here. This will usually be blank. Use a forward slash before the folder name but not after, like so baseurl: '/foldername'
baseurl: 

# This URL points directly to the images directory. It needs a slash at the end.
#
# Example: <img src="http://digitalarcplatform.kalanicraig.com/assets/img/" />
# Markdown-Example for posts ![Image Text](http://digitalarcplatform.kalanicraig.com/assets/img/image.jpg)
#
urlimg: '/assets/img/'
urlitemimg: '/assets/items/'
urlreceptionimg: '/assets/reception/'
permalink: /:categories/:year/:month/:day/:title:output_ext

markdown : kramdown
syntax_highlighter: rouge

# This URL points directly to the images directory. It needs a slash at the end.
exclude :
    - Gemfile
    - Gemfile.lock
    - CNAME
    - LICENSE
    - README.md
    - INSTALL.md
    - vendor/bundle
include: ['_pages']

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  
